FROM python:3.11

RUN apt-get update

WORKDIR /code

COPY requirements.txt .

RUN pip install --no-cache-dir --upgrade -r requirements.txt

COPY gunicorn.conf.py .
COPY main.py .
RUN mkdir -p templates
COPY templates/index.html templates/index.html

# Make port available
EXPOSE 3100  

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "3100", "--proxy-headers"]

