FROM python:3.11

RUN apt-get update
RUN apt-get install -y libreoffice

WORKDIR /code

COPY requirements.txt .

RUN pip install --no-cache-dir --upgrade -r requirements.txt

COPY gunicorn.conf.py .
COPY main.py .

# Make port available
EXPOSE 3100  

#CMD ["python", "main.py"]
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "3100", "--proxy-headers"]

#CMD ["gunicorn", "main:app"]


